spring.application.name=naeko-api

server.port= 1001

# Configurações do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:naekodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console do H2 (Para você visualizar os dados no navegador)
spring.h2.console.enabled=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Aumenta a performance de inserções em lote
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true